security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory: { memory: ~ }
    my_provider:
      entity: { class: Authenticator }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      logout:
        path: /logout
        target: /login
      logout_on_user_change: true

      guard:
        authenticators:
        - App\Security2\AuthenticatorProvider
        - App\Security2\GoogleAuthenticator



      # activate different ways to authenticate

      # http_basic: true
      # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

      # form_login: true
      # https://symfony.com/doc/current/security/form_login_setup.html

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
  # - { path: ^/admin, roles: ROLE_ADMIN }
  # - { path: ^/profile, roles: ROLE_USER }

knpu_oauth2_client:
  clients:
    google:
      # must be "google" - it activates that type!
      type: google
      # add and configure client_id and client_secret in parameters.yml
      client_id: '%env(resolve:GOOGLE_CLIENT_ID)%'
      client_secret: '%env(resolve:GOOGLE_CLIENT_SECRET)%'
      # a route name you'll create
      redirect_route: connect_google_check
      redirect_params: {}